# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3402d1afcdf1e8ac31cf20695ee8d3dc9cce34bd2df6ef9ec767d960466eae3db13164bf6551e1932beaf8e4af9dc270335e6a244bf85b998ce9e7a213efd597

test:
  secret_key_base: 9737d74b0df43f1c9616e594926fbc55f97b4b2454f786711c737fe13b3180cffe90563245a9c85fc4cdee8cc01e421240112db30c564f1f44dcf2dac4e80210

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
